Add -markerlib and pkg-resources to the list of PACKAGES_TO_IGNORE
On Debian unstable, mkvirtualenv 15.0.0 is installing two pseudo
packages (each with a version number of 0.0.0) as can be seen here:

	$ mkvirtualenv foo
	Running virtualenv with interpreter /usr/bin/python2
	New python executable in /home/cworth/.virtualenvs/foo/bin/python2
	Also creating executable in /home/cworth/.virtualenvs/foo/bin/python
	Installing setuptools, pkg_resources, _markerlib, pip, wheel...done.

But then pip-sync will try to uninstall these packages (since nothing
explicitly depends on them) which will then cause pip stop working as
can be seen here:

	$ pip-sync reqs.txt
	Uninstalling pkg-resources-0.0.0:
	  Successfully uninstalled pkg-resources-0.0.0

	$ pip-sync reqs.txt
	Traceback (most recent call last):
	  File "/home/cworth/.virtualenvs/foo/bin/pip-sync", line 5, in <module>
	    from pkg_resources import load_entry_point
	ImportError: No module named pkg_resources

This commit adds these two package names to the PACKAGES_TO_IGNORE
list so that pip-sync will not try to uninstall them.