Generating hashes of distributions should not interfere with each other
Some distributions have incompatible type of files with same name
on the root directory. For example, matplotlib-2.0.2.tar.gz has a
directory named "LICENSE" on the root, which may conflict many
other distributions, causing errors like:

  IOError: [Errno 20] Not a directory: u'/tmp/tmpz/LICENSE/LICENSE_STIX'

So we need to isolate unpacking directory of each distributions.